#!/usr/bin/env python
import json
import sys
import os
import httplib
import socket
import getopt

debug = 'F'
statname = "ok"
statport = "18999"

def bug(msg):
        if debug == 'T':
                print "DEBUG: %s" % msg

def usage():
  print sys.argv[0] + """ [options] [appname]
  options:

  -h/--help         -  print usage summary
  -a/--add          -  add to a pool
  -d/--del          -  delete from a pool
  -s/--server       -  run add/delete against a server
"""

add = "False"
delete = "False"
server = "Null"

try:                                
    opts, remainder = getopt.gnu_getopt(sys.argv[1:], "hads:", ["help", "add=", "del=", "server="])
except getopt.GetoptError:          
    usage()                         
    sys.exit(2)                     
for opt, arg in opts:                
    if opt in ("-h", "--help"):      
        usage()                     
        sys.exit()                  
    elif opt in ("-d", "--del"):
        delete = "True"
    elif opt in ("-a", "--add"):
        add = "True"
    elif opt in ("-s", "--server"):
	server = arg

if len(remainder) < 1:
	usage()
	sys.exit()

if ( add == "True" and delete == "True" ):
	print "ERROR: you can only add OR delete a pool!"
	usage()
	sys.exit()

if ( add == "False" and delete == "False" ):
        print "ERROR: you must either add OR delete a pool!"
        usage()
        sys.exit()

if server == "Null":
	server = socket.gethostname()

host = "%s:18001" % server

if add == "True":
	staturl = "http://%s:%s/status" % (server,statport)
	blob = {"id": remainder[0], "url": staturl}
	data = json.dumps(blob)
	connection =  httplib.HTTPConnection(host)
	body_content = 'BODY CONTENT GOES HERE'
	connection.request('POST', '/checks', data)
	result = connection.getresponse()
	print "RESULT: %s - %s" % (result.status, result.reason)

if delete == "True":
	path = "/checks/%s" % remainder[0]
	connection =  httplib.HTTPConnection(host)
	#connection.set_debuglevel(5)
	connection.request('DELETE', path)
	result = connection.getresponse()
	print "RESULT: %s - %s" % (result.status, result.reason)
